package studio.mars.banditfriends.velocity;

import com.google.inject.Inject;import com.velocitypowered.api.command.*;import com.velocitypowered.api.event.Subscribe;import com.velocitypowered.api.event.connection.DisconnectEvent;import com.velocitypowered.api.event.connection.PostLoginEvent;import com.velocitypowered.api.plugin.Plugin;import com.velocitypowered.api.proxy.*;import net.kyori.adventure.text.minimessage.MiniMessage;import org.slf4j.Logger;import org.spongepowered.configurate.ConfigurationNode;import org.spongepowered.configurate.yaml.YamlConfigurationLoader;import java.io.*;import java.nio.file.*;import java.sql.SQLException;import java.util.*;import java.util.concurrent.*;

@Plugin(id="banditfriends",name="BanditFriends",version="1.0.0",authors={"Mars Studios"})
public final class BanditFriendsVelocity {
 private final ProxyServer proxy;private final Logger log;private final Path folder;private final MiniMessage mm=MiniMessage.miniMessage();private final Map<UUID,Request> requests=new ConcurrentHashMap<>();private ConfigurationNode config;private VelocityStorage storage;private record Request(UUID sender,long expires){}
 @Inject public BanditFriendsVelocity(ProxyServer proxy,Logger log,@com.velocitypowered.api.plugin.annotation.DataDirectory Path folder){this.proxy=proxy;this.log=log;this.folder=folder;}
 @Subscribe public void init(com.velocitypowered.api.event.proxy.ProxyInitializeEvent event){try{Files.createDirectories(folder);Path file=folder.resolve("config.yml");if(Files.notExists(file))try(InputStream in=getClass().getResourceAsStream("/config.yml")){Files.copy(in,file);}config=YamlConfigurationLoader.builder().path(file).build().load();storage=new VelocityStorage(config.node("storage","mysql"));register();proxy.getScheduler().buildTask(this,this::heartbeat).repeat(5,TimeUnit.SECONDS).schedule();log.info("BanditFriends Velocity enabled.");}catch(Exception e){throw new RuntimeException("Could not enable BanditFriends Velocity",e);}}
 private void register(){CommandManager cm=proxy.getCommandManager();cm.register(cm.metaBuilder(config.node("commands","friends").getString("vriend")).plugin(this).build(),new Friends());cm.register(cm.metaBuilder(config.node("commands","friendsadmin").getString("vriendenadmin")).plugin(this).build(),new Admin());}
 @Subscribe public void join(PostLoginEvent e){touch(e.getPlayer());}
 @Subscribe public void quit(DisconnectEvent e){touch(e.getPlayer());}
 private void heartbeat(){for(Player p:proxy.getAllPlayers())touch(p);}
 private void touch(Player p){try{storage.touch(p.getUniqueId(),p.getUsername(),System.currentTimeMillis());}catch(SQLException e){log.warn("MySQL operation failed",e);}}
 private final class Friends implements SimpleCommand {
  public void execute(Invocation i){if(!(i.source() instanceof Player p)){msg(i.source(),"player-only",Map.of());return;}String[] a=i.arguments();if(a.length==0){msg(p,"player-only",Map.of());return;}if(a.length==1&&a[0].equalsIgnoreCase("accept")){respond(p,true);return;}if(a.length==1&&a[0].equalsIgnoreCase("deny")){respond(p,false);return;}if(a.length==2&&a[0].equalsIgnoreCase("add")){request(p,a[1]);return;}if(a.length==2&&a[0].equalsIgnoreCase("remove")){remove(p.getUniqueId(),resolve(a[1]),true);return;}p.sendMessage(mm.deserialize("<red>Usage: /vriend <add|remove|accept|deny> [player]</red>"));}
  public List<String> suggest(Invocation i){return i.arguments().length==1?List.of("add","remove","accept","deny"):List.of();}
 }
 private final class Admin implements SimpleCommand {
  public boolean hasPermission(Invocation i){return i.source().hasPermission("banditfriends.admin");}
  public void execute(Invocation i){String[] a=i.arguments();if(a.length==1&&a[0].equalsIgnoreCase("reload")){try{config=YamlConfigurationLoader.builder().path(folder.resolve("config.yml")).build().load();msg(i.source(),"reloaded",Map.of());}catch(IOException e){i.source().sendMessage(mm.deserialize("<red>Reload failed.</red>"));}return;}if(a.length<3){i.source().sendMessage(mm.deserialize("<red>Usage: /vriendenadmin <add|remove> <player> <friend></red>"));return;}UUID owner=resolve(a[1]),friend=resolve(a[2]);if(owner==null||friend==null){msg(i.source(),"player-not-found",Map.of());return;}try{if(a[0].equalsIgnoreCase("add"))storage.add(owner,friend,System.currentTimeMillis());else if(a[0].equalsIgnoreCase("remove"))storage.remove(owner,friend);}catch(SQLException e){log.warn("MySQL operation failed",e);}}
 }
 private void request(Player from,String targetName){UUID target=resolve(targetName);if(target==null){msg(from,"player-not-found",Map.of());return;}if(target.equals(from.getUniqueId())){msg(from,"cannot-friend-self",Map.of());return;}try{if(storage.friends(from.getUniqueId()).contains(target)){msg(from,"already-friends",Map.of("target",targetName));return;}int max=config.node("limits","max-friends").getInt(10);if(max>=0&&storage.friends(from.getUniqueId()).size()>=max){msg(from,"max-friends-reached",Map.of("max",""+max));return;}Optional<Player> receiver=proxy.getPlayer(target);if(receiver.isEmpty()){msg(from,"player-not-found",Map.of());return;}int sec=config.node("requests","expiry-seconds").getInt(60);requests.put(target,new Request(from.getUniqueId(),System.currentTimeMillis()+sec*1000L));msg(from,"request-sent",Map.of("target",targetName));msg(receiver.get(),"request-received",Map.of("sender",from.getUsername(),"seconds",""+sec,"accept-command":"vriend accept","deny-command":"vriend deny"));}catch(SQLException e){log.warn("MySQL operation failed",e);}}
 private void respond(Player player,boolean accept){Request r=requests.remove(player.getUniqueId());if(r==null||r.expires<System.currentTimeMillis()){msg(player,"no-request",Map.of());return;}try{if(accept){storage.add(r.sender,player.getUniqueId(),System.currentTimeMillis());msg(player,"request-accepted",Map.of("target",name(r.sender)));proxy.getPlayer(r.sender).ifPresent(p->msg(p,"request-accepted-sender",Map.of("target",player.getUsername())));}else{msg(player,"request-denied",Map.of("sender",name(r.sender)));proxy.getPlayer(r.sender).ifPresent(p->msg(p,"request-denied-sender",Map.of("target",player.getUsername())));}}catch(SQLException e){log.warn("MySQL operation failed",e);}}
 private void remove(UUID owner,UUID friend,boolean notify){if(friend==null){return;}try{if(!storage.friends(owner).contains(friend)){if(notify)proxy.getPlayer(owner).ifPresent(p->msg(p,"not-friends",Map.of("target",name(friend))));return;}storage.remove(owner,friend);if(notify){proxy.getPlayer(owner).ifPresent(p->msg(p,"friend-removed",Map.of("target",name(friend))));proxy.getPlayer(friend).ifPresent(p->msg(p,"removed-by-other",Map.of("target",name(owner))));}}catch(SQLException e){log.warn("MySQL operation failed",e);}}
 private UUID resolve(String name){return proxy.getPlayer(name).map(Player::getUniqueId).orElseGet(()->{try{return storage.byName(name);}catch(SQLException e){return null;}});}
 private String name(UUID id){return proxy.getPlayer(id).map(Player::getUsername).orElse(id.toString());}
 private void msg(CommandSource to,String key,Map<String,String> vars){String text=config.node("messages","prefix").getString("")+config.node("messages",key).getString("<red>Missing message</red>");for(var e:vars.entrySet())text=text.replace("<"+e.getKey()+">",e.getValue());to.sendMessage(mm.deserialize(text));}
}