package studio.mars.banditfriends;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;
import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

public final class BanditFriendsPlugin extends JavaPlugin implements Listener {
  private final MiniMessage mm = MiniMessage.miniMessage();
  private final Map<UUID, Request> requests = new ConcurrentHashMap<>();
  private final List<Command> registered = new ArrayList<>();
  private YamlConfiguration data, gui; private File dataFile; private MySqlStorage mysql;
  private record Request(UUID sender, long expires) {}
  @Override public void onEnable() { saveDefaultConfig(); saveResource("gui.yml", false); loadAll(); getServer().getPluginManager().registerEvents(this,this); registerCommands(); }
  @Override public void onDisable() { for(Player p:Bukkit.getOnlinePlayers()) touch(p); saveData(); if(mysql!=null)mysql.close(); }
  private void loadAll(){ if(mysql!=null)mysql.close(); reloadConfig(); gui=YamlConfiguration.loadConfiguration(new File(getDataFolder(),"gui.yml")); dataFile=new File(getDataFolder(),getConfig().getString("storage.file","friends.yml")); data=YamlConfiguration.loadConfiguration(dataFile); if(getConfig().getString("storage.type","yaml").equalsIgnoreCase("mysql"))try{mysql=new MySqlStorage(this);getLogger().info("Connected to MySQL shared storage.");}catch(Exception e){getLogger().severe("MySQL connection failed: "+e.getMessage()+". Plugin will use YAML.");mysql=null;} }
  private void saveData(){ try { data.save(dataFile); } catch(IOException e){ getLogger().severe("Could not save friends.yml: "+e.getMessage()); } }
  private void registerCommands(){ CommandMap map=Bukkit.getCommandMap(); for(Command c:registered)c.unregister(map); registered.clear(); ConfigurationSection root=getConfig().getConfigurationSection("commands"); if(root==null)return; for(String id:List.of("friends","friendsadmin")){ConfigurationSection s=root.getConfigurationSection(id); if(s==null)continue; String label=s.getString("label",id); DynamicCommand cmd=new DynamicCommand(label,id,s.getString("permission",""),s.getStringList("aliases")); map.register(getName().toLowerCase(Locale.ROOT),cmd); registered.add(cmd);} }
  private final class DynamicCommand extends Command { final String id, permission; DynamicCommand(String name,String id,String permission,List<String> aliases){super(name);this.id=id;this.permission=permission;setAliases(aliases);}
    public boolean execute(CommandSender sender,String label,String[] args){ if(!permission.isBlank()&&!sender.hasPermission(permission)){msg(sender,"no-permission",Map.of());return true;} if(id.equalsIgnoreCase("friends")&&args.length==1&&args[0].equalsIgnoreCase(sub("accept")))return respond(sender,true);if(id.equalsIgnoreCase("friends")&&args.length==1&&args[0].equalsIgnoreCase(sub("deny")))return respond(sender,false); return id.equalsIgnoreCase("friends")?friends(sender,args):admin(sender,args); }
    public List<String> tabComplete(CommandSender sender,String alias,String[] a){ if(id.equalsIgnoreCase("friends")){if(a.length==1)return filter(a[0],List.of("add","remove",sub("accept"),sub("deny")));if(a.length==2&&(a[0].equalsIgnoreCase("add")||a[0].equalsIgnoreCase("remove")))return players(a[1]);} if(id.equalsIgnoreCase("friendsadmin")){if(a.length==1)return filter(a[0],List.of("reload","add","remove","list"));if(a.length==2&&!a[0].equalsIgnoreCase("reload"))return players(a[1]);if(a.length==3&&(a[0].equalsIgnoreCase("add")||a[0].equalsIgnoreCase("remove")))return players(a[2]);} return List.of(); }
  }
  private List<String> filter(String start,List<String> source){return source.stream().filter(x->x.toLowerCase().startsWith(start.toLowerCase())).toList();} private List<String> players(String s){return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(n->n.toLowerCase().startsWith(s.toLowerCase())).toList();}
  private boolean friends(CommandSender sender,String[] a){if(!(sender instanceof Player p)){msg(sender,"player-only",Map.of());return true;} if(a.length==0){open(p);return true;} if(a.length!=2||(!a[0].equalsIgnoreCase("add")&&!a[0].equalsIgnoreCase("remove"))){p.sendMessage(plain("<red>Usage: /"+commandName("friends")+" [add|remove|"+sub("accept")+"|"+sub("deny")+"] <player>"));return true;} OfflinePlayer target=resolve(a[1]);if(target==null){msg(p,"player-not-found",Map.of());return true;}if(a[0].equalsIgnoreCase("add"))request(p,target);else remove(p.getUniqueId(),target.getUniqueId(),true);return true;}
  private boolean respond(CommandSender sender,boolean accept){if(!(sender instanceof Player p)){msg(sender,"player-only",Map.of());return true;}Request r=requests.remove(p.getUniqueId());if(r==null||r.expires<System.currentTimeMillis()){msg(p,"no-request",Map.of());return true;}OfflinePlayer source=Bukkit.getOfflinePlayer(r.sender); if(accept){add(r.sender,p.getUniqueId());msg(p,"request-accepted",Map.of("target",name(source)));if(source.isOnline())msg(source.getPlayer(),"request-accepted-sender",Map.of("target",p.getName()));}else{msg(p,"request-denied",Map.of("sender",name(source)));if(source.isOnline())msg(source.getPlayer(),"request-denied-sender",Map.of("target",p.getName()));}return true;}
  private boolean admin(CommandSender sender,String[] a){if(a.length<1){sender.sendMessage(plain("<red>Usage: /"+commandName("friendsadmin")+" <reload|add|remove|list> ..."));return true;}if(a[0].equalsIgnoreCase("reload")){loadAll();registerCommands();msg(sender,"reloaded",Map.of());return true;}if(a.length<2){sender.sendMessage(plain("<red>Specify a player."));return true;}OfflinePlayer owner=resolve(a[1]);if(owner==null){msg(sender,"player-not-found",Map.of());return true;}if(a[0].equalsIgnoreCase("list")){List<String> f=friends(owner.getUniqueId()).stream().map(u->name(Bukkit.getOfflinePlayer(u))).toList();msg(sender,"admin-list",Map.of("player",name(owner),"amount",""+f.size(),"friends",f.isEmpty()?"-":String.join(", ",f)));return true;}if(a.length<3){sender.sendMessage(plain("<red>Specify the friend."));return true;}OfflinePlayer target=resolve(a[2]);if(target==null){msg(sender,"player-not-found",Map.of());return true;}if(a[0].equalsIgnoreCase("add")){add(owner.getUniqueId(),target.getUniqueId());msg(sender,"admin-added",Map.of("player",name(owner),"target",name(target)));}else if(a[0].equalsIgnoreCase("remove")){remove(owner.getUniqueId(),target.getUniqueId(),false);msg(sender,"admin-removed",Map.of("player",name(owner),"target",name(target)));}return true;}
  private void request(Player from,OfflinePlayer to){if(from.getUniqueId().equals(to.getUniqueId())){msg(from,"cannot-friend-self",Map.of());return;}if(friends(from.getUniqueId()).contains(to.getUniqueId())){msg(from,"already-friends",Map.of("target",name(to)));return;}if(!to.isOnline()){from.sendMessage(plain("<red>That player must be online to receive a request.</red>"));return;}int sec=getConfig().getInt("requests.expiry-seconds",60);requests.put(to.getUniqueId(),new Request(from.getUniqueId(),System.currentTimeMillis()+sec*1000L));msg(from,"request-sent",Map.of("target",name(to)));msg(to.getPlayer(),"request-received",Map.of("sender",from.getName(),"seconds",""+sec,"accept-command",commandName("friends")+" "+sub("accept"),"deny-command",commandName("friends")+" "+sub("deny")));Bukkit.getScheduler().runTaskLater(this,()->{Request r=requests.get(to.getUniqueId());if(r!=null&&r.sender.equals(from.getUniqueId())&&r.expires<=System.currentTimeMillis()){requests.remove(to.getUniqueId());msg(to.getPlayer(),"request-expired",Map.of("sender",from.getName()));}},sec*20L);}
  private void add(UUID a,UUID b){long now=System.currentTimeMillis();try{if(mysql!=null){mysql.add(a,b,now);return;}}catch(Exception e){sqlError(e);}data.set("players."+a+".friends."+b,now);data.set("players."+b+".friends."+a,now);saveData();}
  private void remove(UUID a,UUID b,boolean notify){boolean was=friends(a).contains(b);try{if(mysql!=null)mysql.remove(a,b);else{data.set("players."+a+".friends."+b,null);data.set("players."+b+".friends."+a,null);saveData();}}catch(Exception e){sqlError(e);return;}if(notify&&was){OfflinePlayer t=Bukkit.getOfflinePlayer(b);Player p=Bukkit.getPlayer(a);if(p!=null)msg(p,"friend-removed",Map.of("target",name(t)));if(t.isOnline())msg(t.getPlayer(),"removed-by-other",Map.of("target",name(Bukkit.getOfflinePlayer(a))));}}
  private Set<UUID> friends(UUID id){try{if(mysql!=null)return mysql.friends(id);}catch(Exception e){sqlError(e);return Set.of();}ConfigurationSection s=data.getConfigurationSection("players."+id+".friends");if(s==null)return Set.of();return s.getKeys(false).stream().map(x->{try{return UUID.fromString(x);}catch(Exception e){return null;}}).filter(Objects::nonNull).collect(Collectors.toSet());}
  @EventHandler public void onJoin(PlayerJoinEvent e){Player p=e.getPlayer();touch(p);if(getConfig().getBoolean("requests.notify-friends-on-join",true))for(UUID id:friends(p.getUniqueId())){Player f=Bukkit.getPlayer(id);if(f!=null)msg(f,"friend-joined",Map.of("target",p.getName()));}}
  @EventHandler public void onQuit(PlayerQuitEvent e){touch(e.getPlayer());}
  private void touch(Player p){try{if(mysql!=null){mysql.touch(p,System.currentTimeMillis());return;}}catch(Exception e){sqlError(e);return;}data.set("players."+p.getUniqueId()+".name",p.getName());data.set("players."+p.getUniqueId()+".last-seen",System.currentTimeMillis());saveData();}
  private long since(UUID a,UUID b){try{if(mysql!=null)return mysql.since(a,b);}catch(Exception e){sqlError(e);}return data.getLong("players."+a+".friends."+b);}
  private long seen(UUID id){try{if(mysql!=null)return mysql.seen(id);}catch(Exception e){sqlError(e);}return data.getLong("players."+id+".last-seen");}
  private void open(Player p){int rows=Math.max(1,Math.min(6,gui.getInt("rows",6)));Inventory inv=Bukkit.createInventory(p,rows*9,plain(gui.getString("title","<bold>Friends</bold>")));for(int i=0;i<rows*9;i++)if(i<9||i>=rows*9-9||i%9==0||i%9==8)inv.setItem(i,item("border",Map.of()));List<UUID> fs=new ArrayList<>(friends(p.getUniqueId()));fs.sort(Comparator.comparing(u->name(Bukkit.getOfflinePlayer(u)),String.CASE_INSENSITIVE_ORDER));List<Integer> slots=new ArrayList<>();for(int i=0;i<rows*9;i++)if(!(i<9||i>=rows*9-9||i%9==0||i%9==8))slots.add(i);if(fs.isEmpty()&&!slots.isEmpty())inv.setItem(slots.get(0),item("empty",Map.of()));else for(int i=0;i<Math.min(fs.size(),slots.size());i++){UUID u=fs.get(i);OfflinePlayer f=Bukkit.getOfflinePlayer(u);boolean online=f.isOnline();Map<String,String> ph=Map.of("player",name(f),"friends_since",date(since(p.getUniqueId(),u)),"last_seen",online?"now":ago(seen(u)));inv.setItem(slots.get(i),friendItem(online,ph,u));}p.openInventory(inv);}
  @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p)||!e.getView().title().equals(plain(gui.getString("title","<bold>Friends</bold>"))))return;e.setCancelled(true);ItemStack it=e.getCurrentItem();if(it==null||!it.hasItemMeta()||it.getItemMeta().getPersistentDataContainer().get(new NamespacedKey(this,"friend"),org.bukkit.persistence.PersistentDataType.STRING)==null)return;remove(p.getUniqueId(),UUID.fromString(it.getItemMeta().getPersistentDataContainer().get(new NamespacedKey(this,"friend"),org.bukkit.persistence.PersistentDataType.STRING)),true);p.closeInventory();}
  private ItemStack friendItem(boolean online,Map<String,String> ph,UUID id){ItemStack i=item("friends."+(online?"online":"offline"),ph);ItemMeta m=i.getItemMeta();m.getPersistentDataContainer().set(new NamespacedKey(this,"friend"),org.bukkit.persistence.PersistentDataType.STRING,id.toString());i.setItemMeta(m);return i;}
  private ItemStack item(String path,Map<String,String> ph){Material mat=Material.matchMaterial(gui.getString(path+".material","STONE"));ItemStack i=new ItemStack(mat==null?Material.STONE:mat);ItemMeta m=i.getItemMeta();m.displayName(plain(replace(gui.getString(path+".name",""),ph)));m.lore(gui.getStringList(path+".lore").stream().map(x->plain(replace(x,ph))).toList());i.setItemMeta(m);return i;}
  private OfflinePlayer resolve(String s){Player p=Bukkit.getPlayerExact(s);if(p!=null)return p;try{if(mysql!=null){UUID u=mysql.uuidByName(s);if(u!=null)return Bukkit.getOfflinePlayer(u);}}catch(Exception e){sqlError(e);}for(OfflinePlayer o:Bukkit.getOfflinePlayers())if(o.getName()!=null&&o.getName().equalsIgnoreCase(s))return o;return null;}private String name(OfflinePlayer p){return p.getName()==null?"Unknown":p.getName();}private String date(long n){return n==0?"Unknown":new SimpleDateFormat("dd MMM yyyy",Locale.ENGLISH).format(new Date(n));}private String ago(long n){if(n==0)return "Unknown";long s=Duration.ofMillis(System.currentTimeMillis()-n).toSeconds();if(s<60)return s+"s ago";if(s<3600)return s/60+"m ago";if(s<86400)return s/3600+"h ago";return s/86400+"d ago";}
  private String sub(String id){return getConfig().getString("commands."+id+".subcommand",id);}private String commandName(String id){ConfigurationSection s=getConfig().getConfigurationSection("commands."+id);return s==null?id:s.getString("label",id);}private void sqlError(Exception e){getLogger().warning("MySQL operation failed: "+e.getMessage());}private String replace(String text,Map<String,String> vars){for(var e:vars.entrySet())text=text.replace("<"+e.getKey()+">",e.getValue());return text;}private Component plain(String s){return mm.deserialize(s);}private void msg(CommandSender to,String key,Map<String,String> vars){if(to!=null)to.sendMessage(plain(replace(getConfig().getString("messages.prefix","")+getConfig().getString("messages."+key,""),vars)));}
}
